# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Code With Coco
tagline:          'A _fun_ blog'
baseurl:          /
description:      'My first ever web log'
url:              http://samc1213.github.io 

author:
  name:           'Sam Cohen'
  url:            https://twitter.com/samc1213

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samc1213
